{
  "id": "CVE-2019-5729",
  "details": "Splunk-SDK-Python before 1.6.6 does not properly verify untrusted TLS server certificates, which could result in man-in-the-middle attacks.",
  "aliases": [
    "GHSA-f58w-649r-qjr9",
    "PYSEC-2019-203"
  ],
  "modified": "2025-01-14T08:04:22.303877Z",
  "published": "2019-03-21T16:01:05Z",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://www.splunk.com/view/SP-CAAAQAD"
    }
  ],
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "repo": "https://github.com/splunk/splunk-sdk-python",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "e35783da70be272f761eee2f116b1a3f5a16dcd9"
            }
          ]
        }
      ],
      "versions": [
        "0.1.0",
        "0.1.0a",
        "0.8.0",
        "1.0",
        "1.1",
        "1.2",
        "1.2.1",
        "1.2.2",
        "1.2.3",
        "1.3.0",
        "1.3.1",
        "1.4.0",
        "1.5.0",
        "1.6.0",
        "1.6.1",
        "1.6.2",
        "1.6.3",
        "1.6.4",
        "1.6.5"
      ],
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-5729.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ]
}