{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-14856.json"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "8ce3bd6deaa0a0274a921c0137cbd804ffc312d0"
            },
            {
              "fixed": "9bdb89f740a87bcf760424577ce18a8f68d7a741"
            }
          ],
          "repo": "https://github.com/ansible/ansible",
          "type": "GIT"
        }
      ],
      "versions": [
        "v2.6.0",
        "v2.6.1",
        "v2.6.10",
        "v2.6.11",
        "v2.6.12",
        "v2.6.13",
        "v2.6.14",
        "v2.6.15",
        "v2.6.16",
        "v2.6.17",
        "v2.6.18",
        "v2.6.19",
        "v2.6.2",
        "v2.6.3",
        "v2.6.4",
        "v2.6.5",
        "v2.6.6",
        "v2.6.7",
        "v2.6.8",
        "v2.6.9"
      ]
    }
  ],
  "aliases": [
    "GHSA-6fq2-x65v-v9h7",
    "PYSEC-2019-146"
  ],
  "details": "ansible before versions 2.8.6, 2.7.14, 2.6.20 is vulnerable to a None",
  "id": "CVE-2019-14856",
  "modified": "2025-09-30T07:52:18.470024Z",
  "published": "2019-11-26T14:15:11Z",
  "references": [
    {
      "type": "ADVISORY",
      "url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html"
    },
    {
      "type": "ARTICLE",
      "url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html"
    },
    {
      "type": "ADVISORY",
      "url": "https://access.redhat.com/errata/RHSA-2020:0756"
    },
    {
      "type": "REPORT",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14856"
    }
  ],
  "related": [
    "SUSE-SU-2020:3309-1",
    "openSUSE-SU-2020:0513-1",
    "openSUSE-SU-2020:0523-1",
    "openSUSE-SU-2024:10615-1",
    "openSUSE-SU-2024:14244-1",
    "openSUSE-SU-2024:14536-1"
  ],
  "schema_version": "1.7.3",
  "severity": [
    {
      "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
      "type": "CVSS_V3"
    }
  ]
}