{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2021-46179.json"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "69ca635c4c0ba474e9ca583dbb42e3d028c4533a"
            }
          ],
          "repo": "https://github.com/upx/upx",
          "type": "GIT"
        }
      ],
      "versions": [
        "v1.10",
        "v1.11",
        "v1.90",
        "v1.91",
        "v1.92",
        "v1.93",
        "v1.94",
        "v1.95",
        "v1.96",
        "v2.00",
        "v2.01",
        "v2.90",
        "v2.91",
        "v2.92",
        "v2.93",
        "v3.00",
        "v3.01",
        "v3.02",
        "v3.03",
        "v3.04",
        "v3.05",
        "v3.06",
        "v3.07",
        "v3.08",
        "v3.09",
        "v3.91",
        "v3.92",
        "v3.93",
        "v3.94",
        "v3.95",
        "v3.96",
        "v3.99"
      ]
    }
  ],
  "details": "Reachable Assertion vulnerability in upx before 4.0.0 allows attackers to cause a denial of service via crafted file passed to the the readx function.",
  "id": "CVE-2021-46179",
  "modified": "2025-10-10T03:40:18.453234Z",
  "published": "2023-08-22T19:16:21Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://github.com/upx/upx/issues/545"
    }
  ],
  "schema_version": "1.7.3",
  "severity": [
    {
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
      "type": "CVSS_V3"
    }
  ]
}