{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2018-12679.json"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "last_affected": "357b1afe4d09e6abd79a153111e46a9918b7172c"
            },
            {
              "last_affected": "fe716fff7aec2857761355500ad93b5185c6a427"
            }
          ],
          "repo": "https://github.com/tanganelli/coapthon3",
          "type": "GIT"
        }
      ],
      "versions": [
        "1.0",
        "1.0.1",
        "1.01"
      ]
    }
  ],
  "aliases": [
    "GHSA-c6fm-rgw4-8q73",
    "PYSEC-2019-166"
  ],
  "details": "The Serialize.deserialize() method in CoAPthon3 1.0 and 1.0.1 mishandles certain exceptions, leading to a denial of service in applications that use this library (e.g., the standard CoAP server, CoAP client, example collect CoAP server and client) when they receive crafted CoAP messages.",
  "id": "CVE-2018-12679",
  "modified": "2025-07-29T07:53:47.400770Z",
  "published": "2019-04-02T19:29:00Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://github.com/Tanganelli/CoAPthon3/issues/16"
    }
  ],
  "schema_version": "1.7.0",
  "severity": [
    {
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "type": "CVSS_V3"
    }
  ]
}