{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-10761.json"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "4b22d704e4794af63a5a2d633385fd20948f6f90"
            }
          ],
          "repo": "https://github.com/patriksimek/vm2",
          "type": "GIT"
        }
      ],
      "versions": []
    }
  ],
  "aliases": [
    "GHSA-wf5x-cr3r-xr77"
  ],
  "details": "This affects the package vm2 before 3.6.11. It is possible to trigger a RangeError exception from the host rather than the \"sandboxed\" context by reaching the stack call limit with an infinite recursion. The returned object is then used to reference the mainModule property of the host code running the script allowing it to spawn a child_process and execute arbitrary code.",
  "id": "CVE-2019-10761",
  "modified": "2025-07-01T20:15:54Z",
  "published": "2022-07-13T09:15:08Z",
  "references": [
    {
      "type": "FIX",
      "url": "https://github.com/patriksimek/vm2/commit/4b22d704e4794af63a5a2d633385fd20948f6f90"
    },
    {
      "type": "EVIDENCE",
      "url": "https://github.com/patriksimek/vm2/issues/197"
    },
    {
      "type": "ADVISORY",
      "url": "https://snyk.io/vuln/SNYK-JS-VM2-473188"
    }
  ],
  "related": [
    "SNYK-JS-VM2-473188"
  ],
  "schema_version": "1.7.3",
  "severity": [
    {
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:L/A:L",
      "type": "CVSS_V3"
    }
  ]
}