{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2023-31847.json"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "last_affected": "0da4600d100a9f91dd68c8d38f62008284af2529"
            }
          ],
          "repo": "https://github.com/edp963/davinci",
          "type": "GIT"
        }
      ],
      "versions": [
        "v0.1.0",
        "v0.2.0",
        "v0.2.1",
        "v0.3.0-beta",
        "v0.3.0-beta.1",
        "v0.3.0-beta.2",
        "v0.3.0-beta.3",
        "v0.3.0-beta.4",
        "v0.3.0-beta.5",
        "v0.3.0-beta.6",
        "v0.3.0-beta.7",
        "v0.3.0-beta.8",
        "v0.3.0-beta.9",
        "v0.3.0-rc"
      ]
    }
  ],
  "details": "In davinci 0.3.0-rc after logging in, the user can connect to the mysql malicious server by controlling the data source to read arbitrary files on the client side.",
  "id": "CVE-2023-31847",
  "modified": "2025-10-21T13:16:08.009342Z",
  "published": "2023-05-17T01:15:10Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://github.com/edp963/davinci/issues/2326"
    }
  ],
  "schema_version": "1.7.3",
  "severity": [
    {
      "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
      "type": "CVSS_V3"
    }
  ]
}