{
  "affected": [
    {
      "database_specific": {
        "fixed_range": "cfa05470fe534497fc6548e65568d26dab00653a:1af95a20b81624f64c4b19794cb3ca991e6d0a76",
        "introduced_range": "aef4bfbd61798ecc21d94c873b679fbdeaf92462:79601d2d060be52e673a82ed1c46f4666eb28255",
        "source": "https://github.com/google/oss-fuzz-vulns/blob/main/vulns/draco/OSV-2021-1176.yaml"
      },
      "ecosystem_specific": {
        "severity": "MEDIUM"
      },
      "package": {
        "ecosystem": "OSS-Fuzz",
        "name": "draco",
        "purl": "pkg:generic/draco"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "25484b31235d1a35fa72be6ce8d1f7f286b5c0bf"
            },
            {
              "fixed": "1af95a20b81624f64c4b19794cb3ca991e6d0a76"
            }
          ],
          "repo": "https://github.com/google/draco",
          "type": "GIT"
        }
      ],
      "versions": [
        "1.4.0",
        "1.4.1",
        "1.4.3",
        "1.5.0",
        "1.5.1",
        "1.5.2"
      ]
    }
  ],
  "details": "OSS-Fuzz report: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37705\n\n```\nCrash type: Index-out-of-bounds\nCrash state:\ndraco::MeshEdgebreakerTraversalValenceDecoder::DecodeSymbol\ndraco::MeshEdgebreakerDecoderImpl<draco::MeshEdgebreakerTraversalValenceDecoder>\ndraco::MeshEdgebreakerDecoderImpl<draco::MeshEdgebreakerTraversalValenceDecoder>\n```\n",
  "id": "OSV-2021-1176",
  "modified": "2022-07-08T00:09:40.094418Z",
  "published": "2021-08-29T00:00:08.242884Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37705"
    }
  ],
  "schema_version": "1.6.0",
  "summary": "Index-out-of-bounds in draco::MeshEdgebreakerTraversalValenceDecoder::DecodeSymbol"
}