{
  "affected": [
    {
      "database_specific": {
        "source": "https://github.com/google/oss-fuzz-vulns/blob/main/vulns/unicorn/OSV-2021-939.yaml"
      },
      "ecosystem_specific": {
        "severity": null
      },
      "package": {
        "ecosystem": "OSS-Fuzz",
        "name": "unicorn",
        "purl": "pkg:generic/unicorn"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "34ddafcbcf6d16508a63623a68715394ea4e12d8"
            },
            {
              "fixed": "772558119af66269742fe4dcc45ec6000a5a6ea7"
            },
            {
              "fixed": "34ddafcbcf6d16508a63623a68715394ea4e12d8"
            }
          ],
          "repo": "https://github.com/unicorn-engine/unicorn.git",
          "type": "GIT"
        }
      ],
      "versions": [
        "1.0.3"
      ]
    }
  ],
  "details": "OSS-Fuzz report: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35912\n\n```\nCrash type: Segv on unknown address\nCrash state:\nhelper_uc_tracecode\n```\n",
  "id": "OSV-2021-939",
  "modified": "2023-02-24T01:32:43.286841Z",
  "published": "2021-07-09T00:01:18.848024Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35912"
    }
  ],
  "schema_version": "1.7.0",
  "summary": "Segv on unknown address in helper_uc_tracecode"
}