{
  "id": "CVE-2022-42731",
  "details": "mfa/FIDO2.py in django-mfa2 before 2.5.1 and 2.6.x before 2.6.1 allows a replay attack that could be used to register another device for a user. The device registration challenge is not invalidated after usage.",
  "aliases": [
    "GHSA-vw39-2wj9-4q86",
    "PYSEC-2022-303"
  ],
  "modified": "2024-05-13T21:23:23Z",
  "published": "2022-10-11T14:15:10Z",
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/mkalioby/django-mfa2/blob/0936ea253354dd95cb127f09d0efa31324caef27/mfa/FIDO2.py#L58"
    },
    {
      "type": "WEB",
      "url": "https://github.com/mkalioby/django-mfa2/releases/tag/v2.5.1-release"
    },
    {
      "type": "WEB",
      "url": "https://github.com/mkalioby/django-mfa2/releases/tag/v2.6.1-release"
    }
  ],
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "repo": "https://github.com/mkalioby/django-mfa2",
          "events": [
            {
              "introduced": "4903967c23e7dc515090c26bcacec2b64d8dbe9d"
            },
            {
              "fixed": "5fbb505e98ecdd409330a5c336ad5ec49631b0db"
            }
          ]
        }
      ],
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2022-42731.json"
      },
      "versions": []
    }
  ],
  "schema_version": "1.6.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N"
    }
  ]
}